# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mdGEsl4JdRi3W8dY3_ixxDV2rVFERvNR

##q1
"""

length=float(input("Enter the length of the rectangle:"))
width=float(input("Enter the width of the rectangle:"))
area_of_rectangle = length*width
print("Area of rectangle is:",area_of_rectangle)

"""##Q2"""

weight = float(input("Enter weight:"))
height = float(input("Enter height"))
bmi=(weight/height**2)
print("Your bmi is:",bmi)

"""##Q3"""

dict1={"padmaja":"90","jai":"100","sindhuja":"70"}
print(dict1)

"""##Q4

"""

age=int(input("Enter the age of the user:"))
if age >= 70:
  print("You are a senior citizen")
if age==19 and age==69:
  print("You are middle aged person")
if age < 18:
  print("You are a minor person")

"""##Q5"""

for i in range(1, 51):
  if i % 2 == 0:
    print(i)

"""##Q6"""

password={}
def add(account,password):
  if account in password:
    print("password exists already")
  else:
    print("password is added successfully")
def retrieve(account):
  if account in password:
    print("password for {account}is:passwords{account}")
  else:
   print("no password found")
def main():
  global password
  while(True):
    print("select your option to continue")
    print("1)Add your password")
    print("2)retrieve your password")


  choice=(input("enter your choice:"))
  if choice == '1':
    account = input("enter account name:")
    password = input("enter your password")
    passwords[account]=password
    add(account,password)
  elif choice =='2':
     account = input("enter account name:")
      if account in password:
        print(passwords[account])
      else :
        print("No password is found for the {account}")
main()

"""##Q7"""

def average1(n):
    if len(n) == 0:
        return 0
    total = sum(n)
    return total / len(n)

n = [1,2,3,4,5,6,7,8,9]
avg = average1(n)
print("Average:",avg)

"""##Q8"""

def count_v(string):
    vowels = "ThereIsAnAppleInthetree"
    count = 0
    for char in string:
        if char in vowels:
            count += 1
    return count

input_str = "ThereIsAnAppleInthetree"
print("Number of vowels are:", count_v(input_str))

"""##Q9"""

import datetime
current_d_t = datetime.datetime.now()
print("Current date and time is:", current_d_t)

"""##Q10"""

def addn(n1, n2):
    try:
        res = float(n1) + float(n2)
        return res
    except ValueError:
        return "Error: Both inputs should be numeric."

n1 = input("Enter the first number: ")
n2 = input("Enter the second number: ")

print(addn(n1, n2))

"""##Q11"""

while (True):
    try:
        x= int(input("Please enter a no int: "))
        break
    except ValueError:
        print("Invalid input.")

print("no is:", x)

"""##Q12"""

from ast import Div
def div(dividend, divisor):

    if divisor == 0:
        print(" ERROR")
        return None
    else:
        return dividend / divisor

res = div(10, 2)
print("Result:", res)
res = div(5, 0)
print("Result:", res)

"""##Q13

"""

with open("hello.txt", "w") as a:
    a.write("Hello Python")
print("File has been created")

"""##Q14"""

with open("hello.txt","r") as b:
    b.read()
print(b)

"""##Q15"""

#read and print the content from the created file

with open("hello.txt","a") as c:
    c.append("hii hello")
print(c)